---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingdep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      name: shoppingpod
      labels:
        app: shopping
    spec:
      containers:
        - name: shoppingc0
          image: naveen90234/shopping:39
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingnodeport
spec:
  selector:
    app: shopping
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30007
  type: NodePort
